[features]
seeds = false
skip-lint = false
[programs.localnet]
gif_portal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "node tests/gif-portal.js"
