[features]
seeds = false
skip-lint = false
[programs.devnet]
gif_portal = "4SMxfGZ5MgcJDmwbGUDEYeRx5xmvTMG7xCkyoBWY2UQc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "node tests/gif-portal.js"
